### PR TITLE
Implement USB HID support, and refactoring.

### PR DESCRIPTION
**Pull request by micolous**
* Adds direct support for USB HID tokens with `usb` feature, based on some other code I've written (that I'm fine with relicensing for this).
* Keeps existing `authenticator-rs` based `u2fhid` feature as-is. It'll be good to keep that – this doesn't yet implement those APIs, and there'll need to be some abstraction for this anyway on Windows (with its Webauthn platform API).
* Split off common interface code from `nfc` into new `Transport` and `Token` traits
* Add new `AnyTransport` trait, which can wrap anything that supports the `Transport` trait (so you can support both USB and NFC devices)
* Remove `nfc::apdu` and move its constants/tests elsewhere
* Add `CBORCommand::Response` type
* Disable the reader loop in `nfc_token_info` for now, as it just spams when there's USB devices attached
* Move `nfc::iso7816` into `transport`, as it'll be needed for some CTAPv1 stuff with non-NFC transports
* Revise a bunch of docs to make things less confusing
* Run CI for `nfc` and `usb` features
* Fix a bunch of Clippy warnings and errors in `nfc`

Fixes #

- [x] cargo fmt has been run
- [x] cargo test has been run and passes
- [x] documentation has been updated with relevant examples (if relevant)

### CODE REVIEW

**Review by Firstyear — COMMENTED** [review]
Wow, this looks really good! What else would be needed in your view to get this ready to merge?

**Comment by micolous** [comment]
> Wow, this looks really good! What else would be needed in your view to get this ready to merge?

What's left on my list:

- Get it tested in CI (working on that at the moment)
- Make sure there's enough tests for USB-HID
- Make clippy happy

**Review by Firstyear — DISMISSED** [review]

**Comment by Firstyear** [comment]
There is a conflict, and it also may be worth a rebase with the cbor 2 commit when I merge that (hopefully today .... )

**Comment by micolous** [comment]
Rebased

**Review by Firstyear — APPROVED** [review]

**Pull request merged**
