### PR TITLE
Use owned strings instead of references.

### PR DESCRIPTION
**Pull request by jalcine**
Implements #70.

- [x] cargo fmt has been run
- [x] cargo test has been run and passes
- [x] documentation has been updated with relevant examples (if relevant)

### CODE REVIEW

**Comment by Firstyear** [comment]
Curious what the use case is that makes this not work from a configuration. You should be able to create a struct that stores the String identifies of your site you need, and that's what allows you to get the &str. This is what the ephemeral config does. Why would this need to be a String type, which would imply that this value is dynamically changing?

**Comment by jalcine** [comment]
> [@Firstyear]: Curious what the use case is that makes this not work from a configuration. You should be able to create a struct that stores the String identifies of your site you need, and that's what allows you to get the &str. This is what the ephemeral config does. Why would this need to be a String type, which would imply that this value is dynamically changing?

I'm working on using WebAuthn to do authentication for a self-hostable [IndieAuth](https://indieauth.spec.indieweb.org) server - think OAuth2 but you can use your URL on the Web as the ID. That requires me to be able to define things like the origin and host on the fly.

**Comment by Firstyear** [comment]
@jalcine The issue is that credentials need to be bound to the origin they are registered at. To have this dynamically as you are suggesting could open the possibility a credential registered to one origin can be used on another. That's in violation of the standard and it's intent. 

@agrinman What do you think? We could make origin a property of the credential which would allow this dynamic case. We would send the origin from within the credential during the authentication to ensure it's consistent with how it was registered, and we could then make origin a function argument in registration. More over, I think maybe the "config trait" object is maybe not the best way to handle these things, so perhaps we need to rethink that design?

**Comment by Firstyear** [comment]
cc @ericmarkmartin as you've been looking at this a lot lately and may have thoughts too.

**Comment by agrinman** [comment]
If you're operating multiple RPs you can just have multiple implementors of the webauthn config trait. I don't think this restricts anything. The only way a reference wouldn't work is if you're dynamically generating the rpid each time...

**Comment by Firstyear** [comment]
@agrinman I think that's what they are doing here. They want to dynamically associate a credential to different origin/rp_ids, or they want to have one webauthn config to serve many origins.

Regardless, Alex's response is a good point, you can many different implementations of the webauthn config type with each origins policy defined.

**Comment by ericmarkmartin** [comment]
I also think @agrinman's response makes sense

I also think that as with #63 I think it's probably worth taking some time to think about how we decide which credential properties are defined on configs and which can be passed directly to registration/authentication functions, but providing users with the ability to pass the origin directly into the credential functions might be a footgun as suggested in [your comment](https://github.com/kanidm/webauthn-rs/pull/71#issuecomment-826165664).

**Comment by Firstyear** [comment]
@ericmarkmartin I think we'd only pass in the origin at registration, then it would be a property of the credential and could not be an option in the future. That would bind the credential to that origin for all future authentications.

**Comment by ericmarkmartin** [comment]
@jalcine, I'm curious as to how additionally complicating it would be for you to use multiple implementors of `WebauthnConfig`.

**Comment by Firstyear** [comment]
I think the otherside of this today is that a credential is not bound to a specific webauthn config struct. So they could still put a credential regisitred from one origin/webauthnconfig into another for it's authentication which also would violate some guarantees.

**Comment by ericmarkmartin** [comment]
> @ericmarkmartin I think we'd only pass in the origin at registration, then it would be a property of the credential and could not be an option in the future. That would bind the credential to that origin for all future authentications.

Right, but as you pointed out such a credential could then be used against other origins.

**Comment by ericmarkmartin** [comment]
> I think the otherside of this today is that a credential is not bound to a specific webauthn config struct. So they could still put a credential regisitred from one origin/webauthnconfig into another for it's authentication which also would violate some guarantees.

Hmm I hadn't thought about this

**Comment by jalcine** [comment]
> If you're operating multiple RPs you can just have multiple implementors of the webauthn config trait. I don't think this restricts anything. The only way a reference wouldn't work is if you're dynamically generating the rpid each time...

This is _more or less_ what happens, defining the RP ID on boot because the host to use isn't known until it's read from configuration.

**Comment by Firstyear** [comment]
@jalcine So each RP only hosts one origin and you read it from a config file .... I'm not seeing the issue then?

**Comment by jalcine** [comment]
> @jalcine So each RP only hosts one origin and you read it from a config file .... I'm not seeing the issue then?

I can't seem to pass a `String` to the value here. I'm afraid now that this is my lack of understanding of how to return a `&str` when it can't be borrowed (thus implying this should be a constant value but that's not applicable for my use case).

**Comment by Firstyear** [comment]
Your program order should be:

```
1) Read the config file
2) Create the singular webauthn config struct that you create and have derived webauthnConfig to. 
3) Inside that webatuhn config struct, you give it the string (via clone() or whatever)
4) self.origin.as_str() and it all works. 
```

**Comment by Firstyear** [comment]
And then repeat as many times as you need for each configuration.

**Comment by jalcine** [comment]
Welp, that worked! Thank you @Firstyear - apologies for any inconvenience by this. I'll close the PR as well

**Comment by Firstyear** [comment]
No problem, it's raised some interesting questions that I think @agrinman, @ericmarkmartin and myself should think about in how we approach this :) If you have any other questions, please let us know!

**Pull request closed without merging**
